from .settings import * # noqa

DATABASES = {
    DEFAULT_DATABASE_NAME: dj_database_url.parse(DATABASE_URL),
}

EMAIL_DEST_NOTIFY = config("EMAIL_DEST_NOTIFY", cast=Csv(), default="dest1,dest2")

TABLEAU_TARGET_SITE = config("TABLEAU_TARGET_SITE")
TABLEAU_WORKBOOK = config("TABLEAU_WORKBOOK")
TABLEAU_VIEW = config("TABLEAU_VIEW")
TABLEAU_HOST = config("TABLEAU_HOST")
TABLEAU_USERNAME = config("TABLEAU_USERNAME")
