# Generated by Django 3.1.6 on 2021-09-02 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20210412_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calibre', models.CharField(max_length=255, verbose_name='Tipo de Calibre')),
            ],
        ),
        migrations.CreateModel(
            name='Cartucho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cartucho', models.CharField(max_length=255, verbose_name='Tipo de Cartucho')),
            ],
        ),
        migrations.CreateModel(
            name='CartuchoCalibresApreendidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LocalidadeOperacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidade')),
                ('municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Município')),
                ('bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('endereco_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço de referência')),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeDroga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_droga', models.CharField(max_length=255, verbose_name='Nome da Droga')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='batalhao_responsavel',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='boletim_ocorrencia_pm',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='coordenadas_geo',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='endereco_referencia',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='houve_ocorrencia_operacao',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='nome_comandante_operacao',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='nome_condutor_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='numero_guarnicoes_mobilizadas',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='numero_ordem_operacoes',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='numero_policiais_mobilizados',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='numero_presos',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='posto_comandante_operacao',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='posto_condutor_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='rg_pm_comandante_operacao',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='rg_pm_condutor_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='tipo_acao_repressiva',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='unidade_apoiadora',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='batalhao_responsavel',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='boletim_ocorrencia_pm',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='coordenadas_geo',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='endereco_referencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='houve_ocorrencia_operacao',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='nome_comandante_operacao',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='nome_condutor_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='numero_guarnicoes_mobilizadas',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='numero_ordem_operacoes',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='numero_policiais_mobilizados',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='numero_presos',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='posto_comandante_operacao',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='posto_condutor_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='rg_pm_comandante_operacao',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='rg_pm_condutor_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='tipo_acao_repressiva',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='unidade_apoiadora',
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de início da operação'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de término da operação'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='houve_disparados_aeronave',
            field=models.BooleanField(blank=True, null=True, verbose_name='Houve disparos embarcado da aeronave?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='houve_registros_imagem',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foram feitos registros de imagem a partir da aeronave?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='local_preservado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Local permaneceu preservado?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='matricula_id_delegado_operacao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Matrícula/ID Funcional do Delegado'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='natureza_operacao',
            field=models.CharField(choices=[('NatO I', 'Ações de inteligência'), ('NatO II', 'Cumprimento de Medidas Cautelares Judiciais'), ('NatO III', 'Apoio operacional a outras instituições'), ('NatO IV', 'Prestação de auxílio e assistência em emergências')], max_length=10, null=True, verbose_name='Natureza da operação'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='nome_delegado_operacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Delegado Responsável'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='nome_operacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da operação'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_agentes_mobilizados',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Número de agentes mobilizados'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_carregadores_apreendidos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de carregadores apreendidos'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_equipes_medicas',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de equipes médicas de apoio'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_explosivos_apreendidos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de artefatos explosivos apreendidos'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_inquerito_mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Inquérito Policial mãe'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_municoes_apreendidas',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de munições apreendidas'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_presos_elencados',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de presos elencados nos mandados de prisão'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_presos_flagrante',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de presos em flagrante'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_viaturas_mobilizadas',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de viaturas mobilizadas'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='orgaos_externos',
            field=models.TextField(blank=True, null=True, verbose_name='Órgãos Externos'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='pericia_aeronave',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia da aeronave?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='pericia_iml',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia no IML?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='pericia_local',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia do local?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='pericia_outras',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foram feitas outras perícias?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='pericia_veiculo_blindado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia do veículo blindado?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='pericia_viaturas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia das viaturas?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='tipos_drogas_apreendidas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Drogas apreendidas'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='unidades_apoiadoras',
            field=models.TextField(blank=True, null=True, verbose_name='Unidades Apoiadoras'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de início da operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de término da operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='houve_disparados_aeronave',
            field=models.BooleanField(blank=True, null=True, verbose_name='Houve disparos embarcado da aeronave?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='houve_registros_imagem',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foram feitos registros de imagem a partir da aeronave?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='local_preservado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Local permaneceu preservado?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='matricula_id_delegado_operacao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Matrícula/ID Funcional do Delegado'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='natureza_operacao',
            field=models.CharField(choices=[('NatO I', 'Ações de inteligência'), ('NatO II', 'Cumprimento de Medidas Cautelares Judiciais'), ('NatO III', 'Apoio operacional a outras instituições'), ('NatO IV', 'Prestação de auxílio e assistência em emergências')], max_length=10, null=True, verbose_name='Natureza da operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nome_delegado_operacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Delegado Responsável'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nome_operacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da operação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_agentes_mobilizados',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Número de agentes mobilizados'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_carregadores_apreendidos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de carregadores apreendidos'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_equipes_medicas',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de equipes médicas de apoio'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_explosivos_apreendidos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de artefatos explosivos apreendidos'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_inquerito_mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do Inquérito Policial mãe'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_municoes_apreendidas',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de munições apreendidas'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_presos_elencados',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de presos elencados nos mandados de prisão'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_presos_flagrante',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de presos em flagrante'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_viaturas_mobilizadas',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de viaturas mobilizadas'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='orgaos_externos',
            field=models.TextField(blank=True, null=True, verbose_name='Órgãos Externos'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='pericia_aeronave',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia da aeronave?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='pericia_iml',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia no IML?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='pericia_local',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia do local?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='pericia_outras',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foram feitas outras perícias?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='pericia_veiculo_blindado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia do veículo blindado?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='pericia_viaturas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Foi feita perícia das viaturas?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='tipos_drogas_apreendidas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Drogas apreendidas'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='unidades_apoiadoras',
            field=models.TextField(blank=True, null=True, verbose_name='Unidades Apoiadoras'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_adolescentes_apreendidos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de adolescentes apreendidos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_armas_apreendidas',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de armas apreendidas'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_civis_feridos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de civis feridos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_civis_mortos_npap',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de civis mortos – morte não provocada por agente policiais'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_fuzis_apreendidos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de fuzis apreendidos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_mortes_interv_estado',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de mortes por intervenção de agentes do Estado'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_mortes_policiais',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de mortes policiais'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_policiais_feridos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de policiais feridos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_veiculos_recuperados',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de veículos recuperados'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='registro_ocorrencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registro de Ocorrência apensado'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='tipo_operacao',
            field=models.CharField(choices=[('Pr', 'Programada'), ('Em', 'Emergencial')], max_length=10, null=True, verbose_name='Tipo de operação'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='unidade_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidade da polícia judiciária responsável'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_adolescentes_apreendidos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de adolescentes apreendidos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_armas_apreendidas',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de armas apreendidas'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_civis_feridos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de civis feridos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_civis_mortos_npap',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de civis mortos – morte não provocada por agente policiais'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_fuzis_apreendidos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de fuzis apreendidos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_mortes_interv_estado',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de mortes por intervenção de agentes do Estado'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_mortes_policiais',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de mortes policiais'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_policiais_feridos',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de policiais feridos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_veiculos_recuperados',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de veículos recuperados'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='registro_ocorrencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registro de Ocorrência apensado'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='tipo_operacao',
            field=models.CharField(choices=[('Pr', 'Programada'), ('Em', 'Emergencial')], max_length=10, null=True, verbose_name='Tipo de operação'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='unidade_responsavel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidade da polícia judiciária responsável'),
        ),
        migrations.AddConstraint(
            model_name='operacao',
            constraint=models.CheckConstraint(check=models.Q(numero_fuzis_apreendidos__lte=django.db.models.expressions.F('numero_armas_apreendidas')), name='operations_operacao_nr_fuzis_menorigual_nr_armas'),
        ),
        migrations.AddField(
            model_name='cartuchocalibresapreendidos',
            name='tipo_calibre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.calibre'),
        ),
        migrations.AddField(
            model_name='cartuchocalibresapreendidos',
            name='tipo_cartucho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.cartucho'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='localidade_operacao',
            field=models.ManyToManyField(to='operations.LocalidadeOperacao'),
        ),
    ]
