# Generated by Django 3.1.6 on 2021-09-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_auto_20210902_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='endereco_referencia',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='endereco_referencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='localidade',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='municipio',
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_tjrj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do procedimento (TJRJ)'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='localidade_operacao',
            field=models.ManyToManyField(to='operations.LocalidadeOperacao'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_tjrj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do procedimento (TJRJ)'),
        ),
    ]
