# Generated by Django 3.1.6 on 2021-09-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_auto_20210903_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgaosExternosOperacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orgao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Órgão Externo')),
            ],
        ),
        migrations.CreateModel(
            name='ROApensado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número do RO')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesApoiadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidade Apoiadora')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='orgaos_externos',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='registro_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='tipos_drogas_apreendidas',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='unidades_apoiadoras',
        ),
        migrations.AddField(
            model_name='operacao',
            name='cartuchos_calibres',
            field=models.ManyToManyField(to='operations.CartuchoCalibresApreendidos'),
        ),
        migrations.AlterField(
            model_name='cartuchocalibresapreendidos',
            name='tipo_calibre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Calibre'),
        ),
        migrations.AlterField(
            model_name='cartuchocalibresapreendidos',
            name='tipo_cartucho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Cartucho'),
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='orgaos_externos',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='registro_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='tipos_drogas_apreendidas',
        ),
        migrations.AddField(
            model_name='operacao',
            name='tipos_drogas_apreendidas',
            field=models.ManyToManyField(to='operations.TiposDeDroga'),
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='unidades_apoiadoras',
        ),
        migrations.AlterField(
            model_name='tiposdedroga',
            name='nome_droga',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Droga'),
        ),
        migrations.DeleteModel(
            name='Calibre',
        ),
        migrations.DeleteModel(
            name='Cartucho',
        ),
        migrations.AddField(
            model_name='operacao',
            name='orgaos_externos',
            field=models.ManyToManyField(to='operations.OrgaosExternosOperacao'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='registro_ocorrencia',
            field=models.ManyToManyField(to='operations.ROApensado'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='unidades_apoiadoras',
            field=models.ManyToManyField(to='operations.UnidadesApoiadores'),
        ),
    ]
