# Generated by Django 3.1.6 on 2021-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_auto_20210910_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='houve_apreensao_drogas',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='houve_apreensao_drogas',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='tipos_drogas_apreendidas',
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='droga_cannabis',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Cannabis?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='droga_cocaina',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Cocaína?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='droga_haxixe',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Haxixe?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='droga_outros',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Outros?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='droga_sinteticos',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Sintéticos?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='droga_cannabis',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Cannabis?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='droga_cocaina',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Cocaína?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='droga_haxixe',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Haxixe?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='droga_outros',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Outros?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='droga_sinteticos',
            field=models.BooleanField(default=False, verbose_name='Apreensão de Sintéticos?'),
        ),
    ]
