# Generated by Django 3.1.6 on 2021-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_auto_20210915_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperacao',
            name='natureza_operacao',
            field=models.CharField(choices=[('Ações de inteligência', 'Ações de inteligência'), ('Cumprimento de Medidas Cautelares Judiciais', 'Cumprimento de Medidas Cautelares Judiciais'), ('Apoio operacional a outras instituições', 'Apoio operacional a outras instituições'), ('Prestação de auxílio e assistência em emergências', 'Prestação de auxílio e assistência em emergências')], max_length=255, null=True, verbose_name='Natureza da operação'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='natureza_operacao',
            field=models.CharField(choices=[('Ações de inteligência', 'Ações de inteligência'), ('Cumprimento de Medidas Cautelares Judiciais', 'Cumprimento de Medidas Cautelares Judiciais'), ('Apoio operacional a outras instituições', 'Apoio operacional a outras instituições'), ('Prestação de auxílio e assistência em emergências', 'Prestação de auxílio e assistência em emergências')], max_length=255, null=True, verbose_name='Natureza da operação'),
        ),
    ]
