# Generated by Django 3.1.6 on 2021-09-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_auto_20210915_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperacao',
            name='matricula_id_delegado_operacao',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Matrícula/ID Funcional do Delegado'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='matricula_id_delegado_operacao',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Matrícula/ID Funcional do Delegado'),
        ),
    ]
