# Generated by Django 3.1.6 on 2023-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_auto_20230725_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperacao',
            name='numero_ambulancia',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de ambulancia'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_ambulancia',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de ambulancia'),
        ),
    ]
