# Generated by Django 3.1 on 2023-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_auto_20230831_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='comunicou_escolas_saude',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='hospitais_perto',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='comunicou_escolas_saude',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='hospitais_perto',
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='comunicacao_escola',
            field=models.BooleanField(default=False, verbose_name='Houve comunicação prévia às autoridades de educação?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='comunicacao_saude',
            field=models.BooleanField(default=False, verbose_name='Houve comunicação prévia às autoridades de saúde?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='saude_perto',
            field=models.BooleanField(default=False, verbose_name='Unidades de saúde nas proximidades?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='utilizacao_escola',
            field=models.BooleanField(default=False, verbose_name='Houve utilização de equipamento educacional para baseamento de recursos operacionais?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='utilizacao_saude',
            field=models.BooleanField(default=False, verbose_name='Houve utilização de equipamento de saúde para baseamento de recursos operacionais?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='comunicacao_escola',
            field=models.BooleanField(default=False, verbose_name='Houve comunicação prévia às autoridades de educação?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='comunicacao_saude',
            field=models.BooleanField(default=False, verbose_name='Houve comunicação prévia às autoridades de saúde?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='saude_perto',
            field=models.BooleanField(default=False, verbose_name='Unidades de saúde nas proximidades?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='utilizacao_escola',
            field=models.BooleanField(default=False, verbose_name='Houve utilização de equipamento educacional para baseamento de recursos operacionais?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='utilizacao_saude',
            field=models.BooleanField(default=False, verbose_name='Houve utilização de equipamento de saúde para baseamento de recursos operacionais?'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='escolas_perto',
            field=models.BooleanField(default=False, verbose_name='Escolas nas proximidades?'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='escolas_perto',
            field=models.BooleanField(default=False, verbose_name='Escolas nas proximidades?'),
        ),
    ]
