# Generated by Django 3.1.6 on 2023-09-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0027_auto_20230911_0809'),
        ('operations', '0028_auto_20230831_1342'),
    ]

    operations = [
    ]
