# Generated by Django 3.1 on 2023-11-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_auto_20231128_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperacao',
            name='descricao_analise_risco',
            field=models.TextField(blank=True, null=True, verbose_name='Análise de riscos e medidas de controles de danos colaterais das operações e de disparos de confrontos'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='descricao_analise_risco',
            field=models.TextField(blank=True, null=True, verbose_name='Análise de riscos e medidas de controles de danos colaterais das operações e de disparos de confrontos'),
        ),
    ]
