# Generated by Django 3.1 on 2024-07-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_auto_20231205_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperacao',
            name='houve_entrada_forcada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Houve entrada forçada em domicílio em período noturno?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='houve_entrada_forcada',
            field=models.BooleanField(blank=True, null=True, verbose_name='Houve entrada forçada em domicílio em período noturno?'),
        ),
    ]
