# Generated by Django 3.1 on 2024-07-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_auto_20240701_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperacao',
            name='justificativa_entrada_forcada',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da entrada forçada em domicílio em período noturno'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='justificativa_entrada_forcada',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da entrada forçada em domicílio em período noturno'),
        ),
    ]
