# Generated by Django 3.1 on 2023-11-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_auto_20231128_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperacao',
            name='comunicacao_escola',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve comunicação prévia às autoridades de educação?'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='comunicacao_escola',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve comunicação prévia às autoridades de educação?'),
        ),
    ]
