# Generated by Django 3.1 on 2024-08-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_auto_20240701_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperacao',
            name='canal_comunicacao_escola',
            field=models.TextField(blank=True, null=True, verbose_name='Preencha o canal de comunicação utilizado. Especificando o e-mail, telefone ou aplicativo de mensageria utilizado'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='canal_comunicacao_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Preencha o canal de comunicação utilizado. Especificando o e-mail, telefone ou aplicativo de mensageria utilizado'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='justificativa_omissao_comunicacao_escola',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa para omissão da comunicação às autoridades de educação'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='justificativa_omissao_comunicacao_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa para omissão da comunicação às autoridades de saúde'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='orgao_autoridade_comunicacao_escola',
            field=models.TextField(blank=True, null=True, verbose_name='Quais os órgãos ou autoridades foram alertados?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='orgao_autoridade_comunicacao_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Quais os órgãos ou autoridades foram alertados?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='canal_comunicacao_escola',
            field=models.TextField(blank=True, null=True, verbose_name='Preencha o canal de comunicação utilizado. Especificando o e-mail, telefone ou aplicativo de mensageria utilizado'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='canal_comunicacao_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Preencha o canal de comunicação utilizado. Especificando o e-mail, telefone ou aplicativo de mensageria utilizado'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='justificativa_omissao_comunicacao_escola',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa para omissão da comunicação às autoridades de educação'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='justificativa_omissao_comunicacao_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa para omissão da comunicação às autoridades de saúde'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='orgao_autoridade_comunicacao_escola',
            field=models.TextField(blank=True, null=True, verbose_name='Quais os órgãos ou autoridades foram alertados?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='orgao_autoridade_comunicacao_saude',
            field=models.TextField(blank=True, null=True, verbose_name='Quais os órgãos ou autoridades foram alertados?'),
        ),
    ]
