# Generated by Django 3.1 on 2023-11-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_auto_20231128_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperacao',
            name='utilizacao_escola',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve utilização de equipamento educacional para baseamento de recursos operacionais?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='utilizacao_escola',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve utilização de equipamento educacional para baseamento de recursos operacionais?'),
        ),
    ]
