# Generated by Django 3.1 on 2023-11-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_auto_20231128_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperacao',
            name='comunicacao_saude',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve comunicação prévia às autoridades de saúde?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='saude_perto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Unidades de saúde nas proximidades?'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='utilizacao_saude',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve utilização de equipamento de saúde para baseamento de recursos operacionais?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='comunicacao_saude',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve comunicação prévia às autoridades de saúde?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='saude_perto',
            field=models.BooleanField(blank=True, null=True, verbose_name='Unidades de saúde nas proximidades?'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='utilizacao_saude',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Houve utilização de equipamento de saúde para baseamento de recursos operacionais?'),
        ),
    ]
