# Generated by Django 3.1 on 2024-09-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_auto_20240802_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='utilizacao_escola',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='utilizacao_saude',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='utilizacao_escola',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='utilizacao_saude',
        ),
    ]
