# Generated by Django 3.1 on 2025-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_auto_20240925_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_agentes_mobilizados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de agentes mobilizados'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_agentes_mobilizados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de agentes mobilizados'),
        ),
    ]
