# Generated by Django 3.1 on 2023-12-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_auto_20231130_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperacao',
            name='escolas_perto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Escolas nas proximidades?'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='saude_perto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Unidades de saúde nas proximidades?'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='escolas_perto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Escolas nas proximidades?'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='saude_perto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Unidades de saúde nas proximidades?'),
        ),
    ]
