# Generated by Django 3.1 on 2025-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0034_auto_20250407_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_adolescentes_apreendidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de adolescentes apreendidos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_aeronaves',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de aeronaves'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_ambulancia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de ambulancia'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_armas_apreendidas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de armas apreendidas'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_carregadores_apreendidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de carregadores apreendidos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_civis_feridos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de civis feridos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_civis_mortos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de civis mortos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_equipes_medicas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de equipes médicas de apoio'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_explosivos_apreendidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de artefatos explosivos apreendidos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_fuzis_apreendidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de fuzis apreendidos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_mortes_policiais',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de mortes policiais'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_municoes_apreendidas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de munições apreendidas'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_policiais_feridos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de policiais feridos'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_presos_elencados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de presos elencados nos mandados de prisão'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_presos_flagrante',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de presos em flagrante'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_presos_outros_mandados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de presos indicados em outros mandados de prisão pendentes'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_veiculos_blindados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de veículos blindados'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_veiculos_recuperados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de veículos recuperados'),
        ),
        migrations.AlterField(
            model_name='historicaloperacao',
            name='numero_viaturas_mobilizadas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de viaturas mobilizadas'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_adolescentes_apreendidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de adolescentes apreendidos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_aeronaves',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de aeronaves'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_ambulancia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de ambulancia'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_armas_apreendidas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de armas apreendidas'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_carregadores_apreendidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de carregadores apreendidos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_civis_feridos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de civis feridos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_civis_mortos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de civis mortos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_equipes_medicas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de equipes médicas de apoio'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_explosivos_apreendidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de artefatos explosivos apreendidos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_fuzis_apreendidos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de fuzis apreendidos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_mortes_policiais',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de mortes policiais'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_municoes_apreendidas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de munições apreendidas'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_policiais_feridos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de policiais feridos'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_presos_elencados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de presos elencados nos mandados de prisão'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_presos_flagrante',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de presos em flagrante'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_presos_outros_mandados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de presos indicados em outros mandados de prisão pendentes'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_veiculos_blindados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de veículos blindados'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_veiculos_recuperados',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de veículos recuperados'),
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_viaturas_mobilizadas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de viaturas mobilizadas'),
        ),
    ]
